### ISSUE TITLE
Space Mama's Crater first enemies are not changed

### ISSUE THREAD

**Issue by Alby1987** [Snaggly/RaYCiSS#1]
Hi! I'm using the last 1.1.1 RayCiSS on the last 1.1.4 Redemption.

During the level "Space Mama's Crater" the enemies are the Redemption version, not the 1996 original version. At first I tought the patch didn't work, but in "Pencil Penthatlon" they are correctly changed: maybe is something about their facing?

![image](https://user-images.githubusercontent.com/8544258/100537277-5076ac00-3227-11eb-8dc8-8ce560e14f7f.png)

These are the checksums of data.win after the patch

Thanks a lot for your patch!

**Comment by Snaggly** [comment]
Hello!

I quickly played over few levels but couldn't find anything out of the ordinary.

If you're talking about these below, that was from the 1995 original.
![Screenshot_20201129_100815](https://user-images.githubusercontent.com/1353354/100537749-57072280-322b-11eb-9b54-4f33fb306ad4.png)

Thats the new Redemption sprite:
![Screenshot_20201129_100643](https://user-images.githubusercontent.com/1353354/100537769-8b7ade80-322b-11eb-9326-1b511781cf5f.png)

If i did miss out something please let me know where you saw the redemption sprite in what level, in what section. Thank you!

**Comment by Alby1987** [comment]
Hi! So, I tought that the eye patches were not in the original (I didn't notice in my firsto playtrough).

So... False alarm! Sorry for having bothered you, and many thanks for your patch :D
