### ISSUE TITLE
Question about how to use this

### ISSUE THREAD

**Issue by Virgil134** [Snaggly/RaYCiSS#2]
Hey sorry to bother you, but how exactly do I use this tool? The description says I should simply drag the "data.win" from Rayman Redemption into "the Windows executable or the console", but I don't see any .exe files after downloading this.

I'm probably just misunderstanding something here, but yeah I can't get it work since I'm not sure what to do exactly with the data.win file.

**Comment by Snaggly** [comment]
The compiled binary is under the releases tab: https://github.com/Snaggly/RaYCiSS/releases

If that helped solving your issue, let me know

**Comment by Virgil134** [comment]
Ah, I got it to work! Thank you very much for helping me and making this!
